baseURL: "https://blockchain.votolegal.com.br"
defaultContentLanguage: "pt"
enableGitInfo: true
enableMissingTranslationPlaceholders: true
enableRobotsTXT: true
disableHugoGeneratorInject: true
disableKinds:
  - "section"
  - "taxonomy"
  - "taxonomyTerm"
  - "RSS"
  - "sitemap"
footnoteReturnLinkContents: "↩"
googleAnalytics: ""
languageCode: "pt-br"
menu:
  header:
  - identifier: "search"
    name: "Busca"
    url: "#search"
    weight: 1
  - identifier: "results"
    name: "Registros"
    url: "#results"
    weight: 2
  - identifier: "faq"
    name: "FAQ"
    url: "#faq"
    weight: 3
metaDataFormat: "yaml"
title: "Blockchain explorer"
params:
  credits: "uma iniciativa APPCÍVICO"
  disclaimer: "Voto Legal é uma plataforma aberta e baseada em software livre. Os realizadores não se responsabilizam pelas informações fornecidas pelos candidatos, nem pelo comportamento deles durante o período eleitoral, e se eleitos, durante seus respectivos mandatos. Este projeto é distribuido sob a licença **Affero General Public License**."
  mailchimpNewsletterFormAction: "https://votolegal.list-manage.com/TK"
  siteDescription: ""
  tagline: ""
  twitterUsername: ""
  shareImages:
    default: ""
    twitter: ""
    facebook: ""
  socialNetworksLinks:
    medium: https://medium.com/app-civico
    facebook: https://www.facebook.com/AppCivicoCSB
    github: https://github.com/AppCivico
